### ISSUE TITLE
Library Limitations

### ISSUE THREAD

**Issue by zeerakvidizmo** [groupdocs-redaction/GroupDocs.Redaction-for-.NET#12]
While creating policy for ImageAreaRedaction incase of embedded images in PDF, there is not option to provide specific page number.
This would make it possible to redact embedded image on a specific page.

**Comment by AlexanderSObraztsov** [comment]
Hi @zeerakvidizmo
The ImageAreaRedaction is format-independent. Once specified, the same redaction is applied to a PNG image file and the embedded images inside a PDF file. We will consider adding a separate mechanism of filters (page range, etc.) for all available redactions, not only ImageAreaRedaction, and making it a part of redaction policies. 

Before it is implemented, you can try the following options:
1) If you know how much images are on a page (e.g. two: footer and header) or can identify the required image in other way, you can use the [redaction callback feature](https://docs.groupdocs.com/redaction/net/use-redaction-callback/) to accept image redaction only on the specific images and reject on all others. In this case you will have to do "image to page" mapping on your own, depending on your format, etc. 
2) Redaction classes are not sealed, so you can inherit and override the ApplyTo() method. 

Although the custom redaction classes are not supported by RedactionPolicy directly, you can always create a RedactionPolicy instance in runtime and populate it with redactions, loaded using standard XML policy file and add redactions, instantiated in your code.

**Comment by zeerakvidizmo** [comment]
Hi @AlexanderSObraztsov  Thanks for the explanation.
